### PR TITLE
feat(tekton): tekton pipeline run list sort

### PR DESCRIPTION
**Pull request by invincibleJai**
Tracks : https://github.com/janus-idp/backstage-plugins/issues/237

**Screenshots:**

- Pipeline Run List with data

image

- Empty state (will show warning if unable to fetch resource else just empty state)

image

### CODE REVIEW

**Comment by debsmita1** [comment]
do we disable the dropdown if there's only one cluster ?

**Comment by invincibleJai** [comment]
> do we disable the dropdown if there's only one cluster ?

we have similar experience in topology as well, we can take it up as a separate PR

**Comment by debsmita1** [comment]
Are we not showing the "Pipeline Runs" heading anymore when the list is not empty ?

**Comment by debsmita1** [comment]
verified the changes locally.
LGTM !

**Pull request merged**
