### PR TITLE
feat(deps): update to backstage 1.27

### PR DESCRIPTION
**Pull request by schultzp2020**
partially fixes: https://issues.redhat.com/browse/RHIDP-2334

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Verified Tekton, Quay and Argocd plugins. No issues were observed, It works as expected! 🎉 

Tekton
Screenshot 2024-05-21 at 11 59 16 AM

Argocd:
image

Quay:
Screenshot 2024-05-21 at 11 59 30 AM

**Comment by nickboldt** [comment]
I would say we cannot merge this until we figure out the plugin version bumping requirements for the plugins that might need patching for 1.2.z.

**Review by nickboldt — DISMISSED** [review]
Approving based on the fact that this is a `feat` update and will bump plugin versions to x.y+1.0 so we have space to do (manual) releases in the 1.2.x branch. 

See  https://gitlab.cee.redhat.com/rhidp/rhdh/-/blob/rhdh-1-rhel-9/build/scripts/releasePlugin.sh for the manual plugin release script.

**Comment by nickboldt** [comment]
Adding hold label until @davidfestal is ready.

**Comment by invincibleJai** [comment]
LGTM

**Review by nickboldt — APPROVED** [review]
still /approve and /lgtm

**Pull request merged**
