### PR TITLE
feat(lightspeed): implement RHDH user authentication and POST /conversations in lightspeed backend

### PR DESCRIPTION
**Pull request by yangcao77**
This PR implements: https://issues.redhat.com/browse/DEVAI-45, and also the tests for both success & error case

also implements: https://issues.redhat.com/browse/DEVAI-44 with the `POST /conversations` endpoint, and helper functions for conversation_id generation and parsing, as well as the unit tests. 

backend gets `httpAuth` and `userInfo` from the fetch request, and gets RHDH user entity as the `user_id`

to test with it using github authentication, prereq to have user entity defined, and enable github sign-in resolver
```
auth:
  environment: development
  providers:
    github:
      development:
        clientId: <clientId>
        clientSecret: <clientSecret>
        signIn:
          resolvers:
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers
            - resolver: usernameMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
```
and have the user defined, to match your github account name or email address,  for example
```
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: yangcao77
spec:
  profile:
    displayName: Stephanie Cao
    email: yangcao@redhat.com
  memberOf: [guests]
```
with the above user defined, I got the rhdh user entity be `user:default/yangcao77`. Not that it has a special character `/`, so to pass in as a path.param, will need to call `encodeURIComponent` to encode the value. 
for example, a call to `/conversations/:conversationId`

```
        const baseUrl = await this.discoveryApi.getBaseUrl('lightspeed');
        const conversation_id = 'user:default/yangcao77+1q2w3e4r-abcd123'
        const encoded_conversation_id = encodeURIComponent(conversation_id)
        const resp = await this.fetchApi.fetch(`${baseUrl}/conversations/${encoded_conversation_id}`, {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
          },
        });
  
```

Without calling via frontend plugin will not pass the authentication verification, for example, calling from postman will give you `AuthenticationError` as shown:
Screenshot 2024-10-18 at 2 56 33 PM

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Tested the feature, able to generate a new conversation_id and retrieve the conversations. 🎉 


image

**Comment by karthikjeeyar** [comment]
Sonarcloud check complains for the usage of Math.random to generate session_id, please take a look.

**Comment by yangcao77** [comment]
@karthikjeeyar push a new commit to fix the sonarcloud security complaint, and it's passed now. 
PTAL when you have time. Thanks

**Review by karthikjeeyar — APPROVED** [review]
/lgtm

**Pull request merged**
