### PR TITLE
fix(orchestrator): fix ProcessInstanceDTO mapping

### PR DESCRIPTION
**Pull request by ydayagi**
[FLPATH-1675](https://issues.redhat.com//browse/FLPATH-1675)
https://issues.redhat.com/browse/FLPATH-1675

### CODE REVIEW

**Comment by batzionb** [comment]
This PR has a bug
The name is missing in workflows table
Actually I think the spread operator (...) is suitable for the /overview API because it maps almost one to one the WorkflowOverview to WorklowOverviewDTO
I suggest to simply revert the change in this API
image

**Comment by ydayagi** [comment]
> This PR has a bug The name is missing in workflows table Actually I think the spread operator (...) is suitable for the /overview API because it maps almost one to one the WorkflowOverview to WorklowOverviewDTO I suggest to simply revert the change in this API
> 
> And nice that the unit test caught the bug :)
> 
> image

**Comment by ydayagi** [comment]
> > This PR has a bug The name is missing in workflows table Actually I think the spread operator (...) is suitable for the /overview API because it maps almost one to one the WorkflowOverview to WorklowOverviewDTO I suggest to simply revert the change in this API
> > And nice that the unit test caught the bug :)
> > image

already fixed

**Review by batzionb — APPROVED** [review]

**Pull request merged**
