### PR TITLE
chore(tekton): update tekton to be compatible with backstage 1.18.x

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes: https://github.com/janus-idp/backstage-plugins/issues/776

Updated tekton plugin dependencies to make it compatible with 1.18.4 (latest version)

### CODE REVIEW

**Comment by nickboldt** [comment]
to fix failing tests, cherrypick this commit into your PR: 7841871

**Comment by debsmita1** [comment]
verified this locally
LGTM !

**Comment by divyanshiGupta** [comment]
cc: @invincibleJai

**Review by invincibleJai — APPROVED** [review]
LGTM

**Pull request merged**
