### PR TITLE
fix(keycloak): respect fetch size for members

### PR DESCRIPTION
**Pull request by oliverp**
## Referenced issue:
Fixes: https://github.com/janus-idp/backstage-plugins/issues/805

## Short Conclusions about Possible Implementations
We need to pass a value for the max parameter, already present in the used keycloak api. The fetch size must be propagated, otherwise you will end up fetching only a maximum of 100 users as members of a group, causing wrong data to be used.

There are two ways:
- define a new parameter for member fetch size and pass it to the API call
- re-use the userQuerySize since a member is a user anyway

## Current Implementation
There is no possibility to fetch more than 100. It is uses the default in the keycloak server.

## Changes
We pass the userQuerySize into the fetch of members call per group to retrieve the correct data.

### CODE REVIEW

**Comment by oliverp** [comment]
The failing ```turbo run test``` works fine locally. Is there something missing, why the pipeline fails? Can i improve the patch?

**Comment by oliverp** [comment]
I fixed the wrong access. Now it should work as expected.

**Review by invincibleJai — APPROVED** [review]
LGTM

Thanks @oliverp for your contributions.

**Comment by oliverp** [comment]
When will the patch be shipped?

**Comment by invincibleJai** [comment]
@oliverp can you update commit and title to match plugin name as it's keycloak here

```
fix(keycloak): respect fetch size for members
```

**Comment by invincibleJai** [comment]
> @oliverp can you update commit and title to match plugin name as it's keycloak here
> 
> ```
> fix(keycloak): respect fetch size for members
> ```

can refer to https://github.com/janus-idp/backstage-plugins#requirements for more details. As you would like it to be published soon so will recommend keeping one commit with semantic convention and updating PR title.

**Pull request merged**
