### PR TITLE
feat(ocm)!: add basic permissions to ocm backend plugin

### PR DESCRIPTION
**Pull request by PatAKnight**
## Description

Adds the basic permission `ocm.cluster.read` to the OCM Backend plugin. This is part of an ongoing work to bring the permission framework to the Janus IDP plugins. The updates to the Backend plugin involve protecting the GET status route and the GET status by provider id and cluster name routes.

## Fixes
- Fixes: [RHIDP-1152](https://issues.redhat.com/browse/RHIDP-1152)

### CODE REVIEW

**Comment by PatAKnight** [comment]
cc @divyanshiGupta

**Comment by PatAKnight** [comment]
> Can you update, please, doc with information about third "common" component: https://github.com/janus-idp/backstage-plugins/blob/921cdaa300d1eec8635591c4e1e35d928b0b265d/plugins/ocm/README.md#installation

Can do, will get right on that.

**Review by AndrienkoAleksandr — COMMENTED** [review]
I tested the pull request and it works perfectly. Looks good to me!

**Review by divyanshiGupta — APPROVED** [review]
Thanks @PatAKnight for the PR. Looks good to me.
/lgtm

**Review by AndrienkoAleksandr — APPROVED** [review]

**Pull request merged**
