### PR TITLE
feat(bulk-import): perform more dry-run checks in the `POST /imports` backend endpoint [RHIDP-3339]

### PR DESCRIPTION
**Pull request by rm3l**
**What does this PR do / why we need it:**

The `POST /imports` endpoint supports a `dryRun` parameter, which currently only checks if the specified entities do exist in the catalog. It won't attempt to create any PRs in the specified repos.
This PR adds additional checks:
- if the repo already has a catalog-info YAML file in its default branch; it adds a new possible error string: `CATALOG_INFO_FILE_EXISTS_IN_REPO`
- if the repo is empty; it adds a new possible error string: `REPO_EMPTY`
- if the repo does not have a `.github/CODEOWNERS` file, it adds a new possible error string: `CODEOWNERS_FILE_NOT_FOUND_IN_REPO`

This is needed to improve the related frontend plugin.

**BREAKING CHANGES**:
- The error when the specified entity already exists in the catalog has been renamed from `CONFLICT` to `CATALOG_ENTITY_CONFLICT`
- Previous, when the `dryRun` query param was set to `true`, all items in the request body needed to have a non-blank `catalogEntityName` field, otherwise a `400 Bad Request` was returned. This field is no longer mandatory. If it is missing, the catalog entity check will be skipped, but the new checks will still be performed. So the API now always returns a `202` status with the checks errors.

**Which issue(s) this PR fixes:**

Fixes https://issues.redhat.com/browse/RHIDP-3339

**PR acceptance criteria:**

- [x] Unit tests

- [ ] Integration tests

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

- Add at least one GitHub integration - see https://github.com/janus-idp/backstage-plugins/tree/main/plugins/bulk-import-backend#usage
- Start the bulk import backend:

```
yarn workspace @janus-idp/backstage-plugin-bulk-import-backend run start
```

- Example response:

```json

[
  {
    "errors": [],
    "catalogEntityName": "animated-happiness",
    "repository": {
      "url": "https://github.com/lemra-org-ent-2/animated-happiness",
      "name": "animated-happiness",
      "organization": "lemra-org-ent-2"
    }
  },
  {
    "errors": [
      "CATALOG_ENTITY_CONFLICT",
      "CATALOG_INFO_FILE_EXISTS_IN_REPO"
    ],
    "catalogEntityName": "java-quarkus-starter",
    "repository": {
      "url": "https://github.com/lemra-org-ent-1/java-quarkus-starter",
      "name": "java-quarkus-starter",
      "organization": "lemra-org-ent-1"
    }
  },
  {
    "errors": [
      "REPO_EMPTY",
      "CODEOWNERS_FILE_NOT_FOUND_IN_REPO",
    ],
    "catalogEntityName": "reimagined-octo-spork-empty",
    "repository": {
      "url": "https://github.com/lemra-org/reimagined-octo-spork-empty",
      "name": "reimagined-octo-spork-empty",
      "organization": "lemra-org"
    }
  }
]

```

### CODE REVIEW

**Review by PatAKnight — COMMENTED** [review]
CATALOG_INFO_FILE_EXISTS_IN_REPO
```
curl -X POST http://localhost:7007/api/bulk-import-backend/imports?dryRun=true -d '[{"catalogEntityName": "test-node","repository": {"url": "https://github.com/test-org-pat/test-node", "defaultBranch": "main"}, "catalogInfoContent": "---\napiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: catalog-test-repo\n  annotations:\n    github.com/project-slug: test-org-pat/catalog-test-repo\nspec:\n  type: other\n  lifecycle: unknown\n  owner: user:default/pataknight\n---\n"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v | jq

[
  {
    "errors": [
      "CATALOG_ENTITY_CONFLICT",
      "CATALOG_INFO_FILE_EXISTS_IN_REPO"
    ],
    "catalogEntityName": "test-node",
    "repository": {
      "url": "https://github.com/test-org-pat/test-node",
      "name": "test-node",
      "organization": "test-org-pat"
    }
  }
]

```

REPO_EMPTY
```
curl -X POST http://localhost:7007/api/bulk-import-backend/imports?dryRun=true -d '[{"catalogEntityName": "catalog-test-repo","repository": {"url": "https://github.com/test-org-pat/catalog-test-repo", "defaultBranch": "main"}, "catalogInfoContent": "---\napiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: catalog-test-repo\n  annotations:\n    github.com/project-slug: test-org-pat/catalog-test-repo\nspec:\n  type: other\n  lifecycle: unknown\n  owner: user:default/pataknight\n---\n"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v | jq

[
  {
    "errors": [
      "REPO_EMPTY"
    ],
    "catalogEntityName": "catalog-test-repo",
    "repository": {
      "url": "https://github.com/test-org-pat/catalog-test-repo",
      "name": "catalog-test-repo",
      "organization": "test-org-pat"
    }
  }
]

```

Overall, it looks good. Quick question, were you planning on resolving the sonarcloud issue in this PR?

**Comment by rm3l** [comment]
> CATALOG_INFO_FILE_EXISTS_IN_REPO
> 
> ```
> curl -X POST http://localhost:7007/api/bulk-import-backend/imports?dryRun=true -d '[{"catalogEntityName": "test-node","repository": {"url": "https://github.com/test-org-pat/test-node", "defaultBranch": "main"}, "catalogInfoContent": "---\napiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: catalog-test-repo\n  annotations:\n    github.com/project-slug: test-org-pat/catalog-test-repo\nspec:\n  type: other\n  lifecycle: unknown\n  owner: user:default/pataknight\n---\n"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v | jq
> 
> [
>   {
>     "errors": [
>       "CATALOG_ENTITY_CONFLICT",
>       "CATALOG_INFO_FILE_EXISTS_IN_REPO"
>     ],
>     "catalogEntityName": "test-node",
>     "repository": {
>       "url": "https://github.com/test-org-pat/test-node",
>       "name": "test-node",
>       "organization": "test-org-pat"
>     }
>   }
> ]
> ```
> 
> REPO_EMPTY
> 
> ```
> curl -X POST http://localhost:7007/api/bulk-import-backend/imports?dryRun=true -d '[{"catalogEntityName": "catalog-test-repo","repository": {"url": "https://github.com/test-org-pat/catalog-test-repo", "defaultBranch": "main"}, "catalogInfoContent": "---\napiVersion: backstage.io/v1alpha1\nkind: Component\nmetadata:\n  name: catalog-test-repo\n  annotations:\n    github.com/project-slug: test-org-pat/catalog-test-repo\nspec:\n  type: other\n  lifecycle: unknown\n  owner: user:default/pataknight\n---\n"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v | jq
> 
> [
>   {
>     "errors": [
>       "REPO_EMPTY"
>     ],
>     "catalogEntityName": "catalog-test-repo",
>     "repository": {
>       "url": "https://github.com/test-org-pat/catalog-test-repo",
>       "name": "catalog-test-repo",
>       "organization": "test-org-pat"
>     }
>   }
> ]
> ```
> 
> Overall, it looks good. Quick question, were you planning on resolving the sonarcloud issue in this PR?

@PatAKnight Thanks for reviewing this PR. I've refactored it to fix the issues reported by SonarCloud (mostly code duplication).

**Review by AndrienkoAleksandr — APPROVED** [review]
Looks good to me.

**Pull request merged**
