### PR TITLE
fix(rbac): update rbac common to fix compilation

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
# What does this pull request do:

Update rbac common to fix RBAC plugin compilation .

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
@AndrienkoAleksandr Orchestrator backend also uses rbac-common plugin - https://github.com/janus-idp/backstage-plugins/blob/main/plugins/orchestrator-backend/package.json#L88, this needs to be updated as well ?

**Comment by karthikjeeyar** [comment]
FYI, I tried to bump the rbac-common in my permission support for argocd PR, but still it failed with [build errors](https://github.com/janus-idp/backstage-plugins/actions/runs/9716200284/job/26819291270?pr=1855). I will revert my changes in that PR in favour of this one.

**Comment by batzionb** [comment]
changes in orchestrator look good
Is there a need for changes in yarn.lock?

**Pull request merged**
