### PR TITLE
chore(deps): update to backstage 1.23.0

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Story: https://issues.redhat.com/browse/RHIDP-1374

This PR upgrades this repo to backstage 1.23.0. 

Upgrade template - https://backstage.github.io/upgrade-helper/?from=1.22.2&to=1.23.0

### CODE REVIEW

**Review by batzionb — APPROVED** [review]

**Comment by batzionb** [comment]
verified orchestrator plugin

**Comment by invincibleJai** [comment]
Thanks @divyanshiGupta , Have verified below plugins

- aap-backend

image

- RBAC UI

image

- Topology

image


- Tekton

image

- ACR

image

- Quay

image

**Comment by yashoswalyo** [comment]
I've verified feedback plugin, its working as expected.
- Feedback
image
image

**Review by gashcrumb — APPROVED** [review]

**Pull request merged**
