### PR TITLE
feat(kiali): workloads details page overview tab

### PR DESCRIPTION
**Pull request by josunect**
Kiali page for workloads details.

### CODE REVIEW

**Comment by aljesusg** [comment]
It would be great make the links blue like kiali standalone. Users need to know that there is a link to another view
image


The overview of a resource looks great but I don't know if you added the breadcumb ind ev env or not I am going to launch it

image

**Comment by aljesusg** [comment]
Yes...we need toa dd the breadcumb and add some screenshot in the README but looks great

image

**Comment by josunect** [comment]
> Yes...we need toa dd the breadcumb and add some screenshot in the README but looks great
> 
> image

I've added the breadcrumb:

image

Still need to fix a couple of things, but, what do you think about the styles?

**Review by aljesusg — APPROVED** [review]
LGFM

**Pull request merged**
