### PR TITLE
feat(deps): update to backstage 1.31

### PR DESCRIPTION
**Pull request by schultzp2020**
fixes https://issues.redhat.com/browse/RHIDP-3904
fixes: https://issues.redhat.com/browse/RHIDP-4241

### CODE REVIEW

**Review by yashoswalyo — COMMENTED** [review]
LGTM

**Comment by schultzp2020** [comment]
> rbac-backend plugins is broken. IdentityService and TokenManager removed and replaced with AuthService and HttpAuthService: [backstage/backstage#26120](https://github.com/backstage/backstage/issues/26120) . We need to fix this code.

This should already be fixed [here](https://github.com/janus-idp/backstage-plugins/pull/2335/files#diff-d618e59746a661ded4e062c04ec470a500528182bf61e5674937d8a507add8baR1). Have you tested the plugin?

**Comment by mareklibra** [comment]
Needs rebase.

Anyway, when trying as it is, I see error when loading permissions at startup.
The landing page /catalog is failing on an exception.
The Orchestrator is broken, most probably transitively to the issues ^^^.

**Comment by AndrienkoAleksandr** [comment]
@schultzp2020 I can provide patch for you https://github.com/janus-idp/backstage-plugins/pull/2359, but I need time to fix unit tests and test how this code works with service to service requests.

**Comment by yangcao77** [comment]
/lgtm
lgtm from lightspeed-backend perspective

**Comment by schultzp2020** [comment]
> Needs rebase.
> 
> Anyway, when trying as it is, I see error when loading permissions at startup. The landing page /catalog is failing on an exception. The Orchestrator is broken, most probably transitively to the issues ^^^.

Please create a PR to fix this. I will be merging the PR tomorrow.

**Comment by karthikjeeyar** [comment]
Tested Tekton, Quay and Lightspeed plugins

/lgtm

**Comment by mareklibra** [comment]
Retested with recent content of this PR and the `orchestrator` works well.

**Comment by debsmita1** [comment]
Tested bulk import plugin
/lgtm

**Comment by its-mitesh-kumar** [comment]
Tested RBAC plugin
/lgtm

**Review by nickboldt — APPROVED** [review]
fire in the hole!
*ducks and covers*

**Pull request merged**
