### PR TITLE
fix(rbac): background color of sidebar in dark theme

### PR DESCRIPTION
**Pull request by ciiay**
[RHIDP-3038](https://issues.redhat.com/browse/RHIDP-3038): [RBAC] conditional Side bar styles are not changing for dark theme

How to test:
1. Pull this PR to your local plugins repo
2. Go to `plugins/rbac` and run `yarn export-dynamic`
3. At your local showcase directory, go to `dynamic-plugins-root/` and run
```
pkg=../../backstage-plugins/plugins/rbac
archive=$(npm pack $pkg)
tar -xzf "$archive" && rm "$archive"
mv package $(echo $archive | sed -e 's:\.tgz$::')
``` 
4. Go to `packages/backend/package.json` and update rbac backend version to `"@janus-idp/backstage-plugin-rbac-backend": "4.3.2"` as current rbac plugin only works with the latest rbac backend version.
5. Go to showcase root directory and run `yarn install` and `yarn start` to start backstage-showcase

Screen recording(updated on 07/16):

https://github.com/user-attachments/assets/cf0b6826-b8e7-4808-aef3-d14a76f48bb7

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@ciiay I see following gaps:

Screenshot 2024-07-15 at 7 59 25 PM

On adding text to params field its background turns light blue

Screenshot 2024-07-15 at 8 03 52 PM

Also I see the buttons and text-fields background color dont match the figma anymore - https://www.figma.com/design/E6C9X3OSVzlWkW7ZsbxN7s/Administration?node-id=4580-5086&t=Wo3veIWIBDMDbUPy-4

cc: @ShiranHi

**Comment by ciiay** [comment]
Hi @divyanshiGupta , thanks for the review.
>Also I see the buttons and text-fields background color dont match the figma anymore -

Which buttons background color do you mean? I only specified the `Save` button to use `primary` color.

**Comment by divyanshiGupta** [comment]
@ciiay I also see text-field selection border colors are different for rule field and params fields

https://github.com/user-attachments/assets/689d1813-7575-4ffa-a87b-10dd0c921c6d

**Comment by divyanshiGupta** [comment]
@ShiranHi PTAL at below screens and give +1 if these looks good to you. Thanks!
Screenshot 2024-07-16 at 1 15 49 PM
Screenshot 2024-07-16 at 1 16 41 PM

**Comment by ShiranHi** [comment]
> @ciiay I also see text-field selection border colors are different for rule field and params fields

That's correct, we need to add background color there, @ciiay is that possible?
This is the design:
image

**Comment by ciiay** [comment]
Hi @divyanshiGupta @ShiranHi , I have updated the screen recording to reflect the PR changes. Please take a look, thank you :)

**Review by divyanshiGupta — APPROVED** [review]

**Pull request merged**
