### PR TITLE
feat(deps): update to backstage 1.32

### PR DESCRIPTION
**Pull request by schultzp2020**
partially fixes https://issues.redhat.com/browse/RHIDP-3910

### CODE REVIEW

**Review by yashoswalyo — CHANGES_REQUESTED** [review]
/lgtm

**Comment by schultzp2020** [comment]
> /lgtm

@yashoswalyo I think you accidently selected request changes.

**Review by PatAKnight — COMMENTED** [review]
Was able to test the following plugins:

- ocm frontend and backend
- rbac frontend and backend
- jfrog artifactory
- quay
- topology
- Keycloak
- Kubernetes actions 

For the kubernetes actions, I needed to add `NODE_OPTIONS=--no-node-snapshot` when starting to be able to properly test it. I am assuming that this will be the case for all of the actions.

**Comment by divyanshiGupta** [comment]
@its-mitesh-kumar can you test the bulk-import plugin?

**Comment by AndrienkoAleksandr** [comment]
backstage-plugins instance is working for me only when I comment custom logger:

```
...
// backend.add(customLogger);
...
```

in the packages/src/backend/index.ts...

Otherwise I see error:

```
backend:start: Loading config from MergedConfigSource{FileConfigSource{path="/private/tmp/backstage-plugins/app-config.yaml"}, EnvConfigSource{count=0}}
backend:start: /private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:215
backend:start:         throw new Error(
backend:start:               ^
backend:start: 
backend:start: 
backend:start: Error: Duplicate service implementations provided for core.rootLogger
backend:start:     at ServiceRegistry.add (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:215:15)
backend:start:     at BackendInitializer.#addFeature (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:164:29)
backend:start:     at BackendInitializer.#applyBackendFeatureLoaders (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:526:16)
backend:start:     at async BackendInitializer.#doStart (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:211:11)
backend:start:     at async BackendInitializer.start (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
backend:start:     at async BackstageBackend.start (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
backend:start: 
backend:start: Node.js v20.17.0
```

**Comment by divyanshiGupta** [comment]
> backstage-plugins instance is working for me only when I comment custom logger:
> 
> ```
> ...
> // backend.add(customLogger);
> ...
> ```
> 
> in the packages/src/backend/index.ts...
> 
> Otherwise I see error:
> 
> ```
> backend:start: Loading config from MergedConfigSource{FileConfigSource{path="/private/tmp/backstage-plugins/app-config.yaml"}, EnvConfigSource{count=0}}
> backend:start: /private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:215
> backend:start:         throw new Error(
> backend:start:               ^
> backend:start: 
> backend:start: 
> backend:start: Error: Duplicate service implementations provided for core.rootLogger
> backend:start:     at ServiceRegistry.add (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:215:15)
> backend:start:     at BackendInitializer.#addFeature (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:164:29)
> backend:start:     at BackendInitializer.#applyBackendFeatureLoaders (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:526:16)
> backend:start:     at async BackendInitializer.#doStart (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:211:11)
> backend:start:     at async BackendInitializer.start (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
> backend:start:     at async BackstageBackend.start (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
> backend:start: 
> backend:start: Node.js v20.17.0
> ```

I am facing the same issue.

**Comment by ciiay** [comment]
Hi @schultzp2020 , I see backstage 1.32.3 is on [yarn 3.8.1](https://github.com/backstage/backstage/blob/patch/v1.32.0/package.json#L136), do we need to match the yarn version for the same backstage version?

**Comment by schultzp2020** [comment]
> > backstage-plugins instance is working for me only when I comment custom logger:
> > ```
> > ...
> > // backend.add(customLogger);
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the packages/src/backend/index.ts...
> > Otherwise I see error:
> > ```
> > backend:start: Loading config from MergedConfigSource{FileConfigSource{path="/private/tmp/backstage-plugins/app-config.yaml"}, EnvConfigSource{count=0}}
> > backend:start: /private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:215
> > backend:start:         throw new Error(
> > backend:start:               ^
> > backend:start: 
> > backend:start: 
> > backend:start: Error: Duplicate service implementations provided for core.rootLogger
> > backend:start:     at ServiceRegistry.add (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/ServiceRegistry.ts:215:15)
> > backend:start:     at BackendInitializer.#addFeature (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:164:29)
> > backend:start:     at BackendInitializer.#applyBackendFeatureLoaders (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:526:16)
> > backend:start:     at async BackendInitializer.#doStart (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:211:11)
> > backend:start:     at async BackendInitializer.start (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackendInitializer.ts:187:5)
> > backend:start:     at async BackstageBackend.start (/private/tmp/backstage-plugins/node_modules/@backstage/backend-app-api/src/wiring/BackstageBackend.ts:38:11)
> > backend:start: 
> > backend:start: Node.js v20.17.0
> > ```
> 
> I am facing the same issue.

@AndrienkoAleksandr @divyanshiGupta fixed in my most recent commit.

**Review by yangcao77 — APPROVED** [review]
lgtm from lightspeed-backend perspective

**Review by AndrienkoAleksandr — COMMENTED** [review]
@schultzp2020 Thanks, you fixed backstage:start command! Pr looks good to me.

**Comment by ciiay** [comment]
Tested bulk import and it works great. Also the github login is working in this latest version. Thank you for doing this 💯 
image

**Comment by its-mitesh-kumar** [comment]
During bulk import testing, I attempted to add this [repository](https://github.com/its-mitesh-kumar/https-github.com-its-mitesh-kumar-national-py).

The API behavior is inconsistent:

Sometimes, the endpoint http://localhost:7007/api/bulk-import/imports?dryRun=true returns a 500 error with the message Invalid URL.
Other times, the endpoint http://localhost:7007/api/bulk-import/imports responds with a status of PR_ERROR.
Occasionally, the repository is added successfully.
Please find the attached screen recording for reference.

Uploading Screen Recording 2024-10-28 at 8.17.09 AM.mov…

**Review by divyanshiGupta — APPROVED** [review]
Thanks @schultzp2020 for the PR. It works as expected. 
Looks like some tests are failing though, once that is fixed I will add lgtm and we can get this PR merged.

**Comment by karthikjeeyar** [comment]
@Eswaraiahsapram can you please test tekton and quay plugins.

**Comment by Eswaraiahsapram** [comment]
@schultzp2020  Thanks, lgtm for Tekton and Quay plugins

**Pull request merged**
