### PR TITLE
feat(bulk-import): add fields for annotations, labels and spec input

### PR DESCRIPTION
**Pull request by ciiay**
For [RHIDP-2927](https://issues.redhat.com//browse/RHIDP-2927)

Screen recording:

https://github.com/user-attachments/assets/6e7c3357-19aa-4884-b376-b4aea167dfce

### CODE REVIEW

**Comment by ShiranHi** [comment]
Looks good to me, thank you!

**Review by debsmita1 — CHANGES_REQUESTED** [review]
@ciiay The newly added fields have no validation

**Review by debsmita1 — CHANGES_REQUESTED** [review]
when you add spec/label/annotations and then remove it, they appear as empty objects in the preview section

Screenshot 2024-08-05 at 9 47 13 PM


Validation works like a charm. Thank you

**Comment by debsmita1** [comment]
Tested it locally and it works fine
Please resolve the 3 issues reported by the quality gate and we will be good to go
Thanks ! :)

**Review by debsmita1 — APPROVED** [review]

**Pull request merged**
