### PR TITLE
chore(cli): janus-cli cleanup

### PR DESCRIPTION
**Pull request by jesuino**
Removing unused commands janus-cli. See [RHIDP-3230](https://issues.redhat.com/browse/RHIDP-3230).

For now we are removing only the `new` command. It was tested following the steps below:
* `packages/cli` build 
* `yarn export-dynamic` on `backstage-plugins`
* `yarn link` on `packages/cli`, then `yarn link "@janus-idp/cli"` on `backstage-showcase` and then `yarn export-dynamic`
* Finally `yarn build` on `backstage-showcase`;

### Why other commands were not removed?

Not removing other commands because they are used in showcase and  we will revisit `package export-dynamic` options after upgrading dynamic plugins and moving plugins to community plugins repo.

The command `package metadata` and `package schema` are not used directly, but were recently added, hence we need to keep it for now.

### CODE REVIEW

**Comment by jesuino** [comment]
Did a few more risky removals and I will refine the removal finding non used lines with [c8](https://www.npmjs.com/package/c8?activeTab=readme). I am adding current c8 coverage report for reference. It was generated using `c8 yarn run export-dynamic` on `backstage-plugins`

```
------------------------------------|---------|----------|---------|---------|----------------------
File                                | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s    
------------------------------------|---------|----------|---------|---------|----------------------
All files                           |   57.93 |     61.4 |   58.94 |   57.93 |                      
 src                                |   81.48 |      100 |     100 |   81.48 |                      
  index.ts                          |   81.48 |      100 |     100 |   81.48 | 36-40,47-51          
 src/commands                       |    93.1 |     87.5 |     100 |    93.1 |                      
  index.ts                          |    93.1 |     87.5 |     100 |    93.1 | 46-52,141-143        
 src/commands/export-dynamic-plugin |   37.58 |    57.69 |      50 |   37.58 |                      
  backend-embed-as-code.ts          |   83.79 |    56.81 |   83.33 |   83.79 | ...9,279-280,328-331 
  backend-embed-as-dependencies.ts  |    6.82 |      100 |       0 |    6.82 | ...0,757-777,779-865 
  backend-utils.ts                  |   44.09 |    66.66 |   28.57 |   44.09 | ...3,125-135,138-161 
  command.ts                        |   90.54 |    55.55 |     100 |   90.54 | 45-46,54,63-66       
  dev.ts                            |   37.75 |       50 |     100 |   37.75 | 37-97                
  frontend.ts                       |   64.23 |    42.85 |     100 |   64.23 | 46-50,60-61,81-127   
  index.ts                          |     100 |      100 |     100 |     100 |                      
 src/commands/install               |     100 |      100 |     100 |     100 |                      
  types.ts                          |     100 |      100 |     100 |     100 |                      
 src/commands/install/steps         |      61 |      100 |      25 |      61 |                      
  dependencies.ts                   |   53.01 |      100 |       0 |   53.01 | 35-71,77,81          
  index.ts                          |     100 |      100 |     100 |     100 |                      
 src/lib                            |   52.58 |    63.63 |   34.78 |   52.58 |                      
  entryPoints.ts                    |   87.17 |    55.55 |     100 |   87.17 | 45-46,54,66-69,76-78 
  errors.ts                         |      50 |      100 |       0 |      50 | 21-22,25-36,38-46    
  parallel.ts                       |   53.44 |       50 |      50 |   53.44 | ...3,114-147,150-174 
  paths.ts                          |     100 |      100 |     100 |     100 |                      
  run.ts                            |   39.13 |      100 |       0 |   39.13 | 42-76,79-92,95-115   
  svgrTemplate.ts                   |      50 |      100 |       0 |      50 | 22-42                
  tasks.ts                          |      39 |    66.66 |    37.5 |      39 | ...7,102-159,162-200 
  version.ts                        |   59.59 |      100 |      50 |   59.59 | 60-99                
 src/lib/builder                    |   66.32 |    63.07 |   84.21 |   66.32 |                      
  buildScalprumPlugin.ts            |     100 |      100 |     100 |     100 |                      
  buildTypeDefinitions.ts           |    22.9 |      100 |       0 |    22.9 | 31-131               
  buildTypeDefinitionsWorker.ts     |   23.71 |      100 |       0 |   23.71 | 24-97                
  config.ts                         |   89.21 |    73.91 |     100 |   89.21 | ...71,99-108,171-177 
  embedPlugin.ts                    |   87.27 |    66.66 |     100 |   87.27 | ...8-69,72-73,99-104 
  index.ts                          |     100 |      100 |     100 |     100 |                      
  packager.ts                       |   48.33 |    33.33 |   66.66 |   48.33 | ...4,106-107,116-117 
  plugins.ts                        |   85.29 |       50 |     100 |   85.29 | ...8,110-111,117-123 
  types.ts                          |     100 |      100 |     100 |     100 |                      
 src/lib/bundler                    |   86.72 |    33.33 |   63.63 |   86.72 |                      
  bundlePlugin.ts                   |   69.92 |    36.36 |      60 |   69.92 | ...1,114-121,123-130 
  paths.ts                          |    97.4 |    57.14 |     100 |    97.4 | 40,48                
  scalprumConfig.ts                 |   91.35 |    14.28 |      50 |   91.35 | 86-95,175-180        
  transforms.ts                     |    89.3 |       20 |      50 |    89.3 | ...1,178-182,197-203 
 src/lib/packager                   |    90.4 |    53.33 |     100 |    90.4 |                      
  productionPack.ts                 |    90.4 |    53.33 |     100 |    90.4 | ...5,157-158,197-198 
 src/lib/schema                     |   86.98 |    79.59 |     100 |   86.98 |                      
  collect.ts                        |   86.98 |    79.59 |     100 |   86.98 | ...3,245-249,252-253 
 src/lib/versioning                 |   31.38 |      100 |       0 |   31.38 |                      
  Lockfile.ts                       |   27.77 |      100 |       0 |   27.77 | 96-342               
  index.ts                          |     100 |      100 |       0 |     100 |                      
------------------------------------|---------|----------|---------|---------|----------------------
```

**Review by gashcrumb — CHANGES_REQUESTED** [review]
Just verified with some local testing we'll want to keep the `package start` and `package build` commands, these are referenced in the backstage-showcase frontend app packages in `packages/app/package.json`

**Comment by jesuino** [comment]
Hello @gashcrumb thanks for your review.

I am removing only the `new` command for now. We can go back to a cleanup later and touch the most dangerous parts (export-dynamic options, schema and metadata)

**Review by gashcrumb — APPROVED** [review]
:+1: nice, it's a great start :smile:

**Pull request merged**
