### PR TITLE
docs(orchestrator): align readme file with main

### PR DESCRIPTION
**Pull request by jkilzi**
This PR aligns the README file in the stable branch with its version in the  main branch

Addresses:
- https://issues.redhat.com/browse/FLPATH-1145

### CODE REVIEW

**Review by caponetto — APPROVED** [review]

**Review by batzionb — APPROVED** [review]

**Comment by jkilzi** [comment]
@tumido PTAL 🙏, we need one more approval

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by jkilzi** [comment]
@tumido isn't it supposed to automerge?
Maybe because it's prefixed with `docs...` it doesn't?

**Comment by batzionb** [comment]
@nickboldt 
Is this PR not merging automatically because it's on a branch?
How can we get it merged?

**Comment by nickboldt** [comment]
To avoid this in future, you should look at migrating to https://github.com/backstage/community-plugins/tree/main/workspaces

**Pull request merged**
