### PR TITLE
fix(quay): fix sorting and ordering of vulneribilities based on severity

### PR DESCRIPTION
**Pull request by rohitkrai03**
## Description
- Fixed the ordering of vulnerabilities in tags list page based on severity.
- Fixed the sorting of vulnerabilities in vulnerabilities list page based on severity.

### Before 

https://github.com/janus-idp/backstage-plugins/assets/6041994/c77dd566-5691-4101-92c5-3ba5f02dca24

### After

https://github.com/janus-idp/backstage-plugins/assets/6041994/1b6f4be1-1234-4665-b580-0532d76e3269

https://github.com/janus-idp/backstage-plugins/assets/6041994/d58a7911-585a-4b73-a792-62d300344bce

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Vulnerability column value order and sorting on vulnerability details page works as expected.


I noticed `SECURITY SCAN` column is missing sorting, good to have this fixed as well, wdyt? 

sorting_security_scan

**Review by karthikjeeyar — APPROVED** [review]
Vulnerability column value order and sorting on vulnerability details page works as expected.
LGTM

**Comment by rohitkrai03** [comment]
> Vulnerability column value order and sorting on vulnerability details page works as expected.
> 
> I noticed `SECURITY SCAN` column is missing sorting, good to have this fixed as well, wdyt?
> 
> sorting_security_scan [ sorting_security_scan ](https://private-user-images.githubusercontent.com/9964343/292182635-6d6172cd-6f0f-4409-84dd-8f346e711ad3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTcwNzksIm5iZiI6MTcwMzE1Njc3OSwicGF0aCI6Ii85OTY0MzQzLzI5MjE4MjYzNS02ZDYxNzJjZC02ZjBmLTQ0MDktODRkZC04ZjM0NmU3MTFhZDMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTEwNjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM0YWFjOTFjYTRiM2MxNDIzODVlMmMyZmU0M2IwNGVkNWI1NGFmMDkzNTdiZWNjYmVmNTViMWU1MmZmMjg1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V2B1p5_i0Vo1U6ttwUd3zM73JZ7ItaMzEcTRcqCazaM) [ ](https://private-user-images.githubusercontent.com/9964343/292182635-6d6172cd-6f0f-4409-84dd-8f346e711ad3.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTcwNzksIm5iZiI6MTcwMzE1Njc3OSwicGF0aCI6Ii85OTY0MzQzLzI5MjE4MjYzNS02ZDYxNzJjZC02ZjBmLTQ0MDktODRkZC04ZjM0NmU3MTFhZDMuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjFUMTEwNjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODM0YWFjOTFjYTRiM2MxNDIzODVlMmMyZmU0M2IwNGVkNWI1NGFmMDkzNTdiZWNjYmVmNTViMWU1MmZmMjg1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V2B1p5_i0Vo1U6ttwUd3zM73JZ7ItaMzEcTRcqCazaM)

The sorting will work to some extent after the fix for infinite loader goes in. Although we do need proper sort handlers for both of the tables (The current ones are the default MUI ones) and that involves a lot more work than what is scope in our current tickets. I feel that work might be another feature in itself which we can track as a separate ticket.  WDYT?

**Comment by karthikjeeyar** [comment]
@rohitkrai03 I agree that it is out of scope for this fix, I will log a new feature request for sorting capabilities. Thanks

**Review by invincibleJai — APPROVED** [review]
LGTM

**Pull request merged**
