### PR TITLE
feat(rbac): show list of accessible plugins in roles list page

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Story: https://issues.redhat.com/browse/RHIDP-2769

Screenshot 2024-07-24 at 6 29 39 PM
Screenshot 2024-07-24 at 6 29 28 PM

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @ShiranHi

**Comment by ShiranHi** [comment]
Looks good to me, thank you!

**Pull request merged**
