### PR TITLE
fix(web-terminal): fix #598: Cleanup some small code smells in the web-terminal plugin

### LINKED ISSUE #598: Reduce code smells in Web terminal plugin
Part of: #583

Investigate code smells in the Tekton plugin and fix them via a PR or explained why they should be dismissed as irrelevant.

See this plugin folder and respective code smells column here:
https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins

### PR DESCRIPTION
**Pull request by jerolimov**
Fix #598: Cleanup 7 code smells reported by sonarcloud:

* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fweb-terminal%2Fsrc%2Fcomponents%2FTerminalComponent%2FTerminalComponent.tsx
  * Checked options in conditions instead of enforcing them with `!`
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fweb-terminal%2Fsrc%2Fcomponents%2FTerminalComponent%2FTerminalComponent.test.tsx
  * switched (hihi) from a switch statement to an if statement because it has just one case
* https://sonarcloud.io/code?id=janus-idp_backstage-plugins&selected=janus-idp_backstage-plugins%3Aplugins%2Fweb-terminal%2Fsrc%2Fcomponents%2FTerminalComponent%2Fstatic%2Fxterm.css
  * removed commented code

### CODE REVIEW

**Review by invincibleJai — APPROVED** [review]
LGTM

**Comment by invincibleJai** [comment]
@jerolimov i see jobs failing, one issue looks with link and other with semantic release so might need to update the commit message

**Comment by mimotej** [comment]
> /cc @mimotej if you want to take a look
other than, these tests failing rest LGTM, thanks 👏

**Review by invincibleJai — APPROVED** [review]

**Pull request merged**
