### PR TITLE
fix(rbac): align styles with UXD

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes: https://issues.redhat.com/browse/RHIDP-1761

It also fixes this test issue https://issues.redhat.com/browse/RHIDP-1831

https://github.com/janus-idp/backstage-plugins/assets/20724543/4469fd77-e547-4e83-a666-6d6759832fdf

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @invincibleJai

**Comment by invincibleJai** [comment]
@divyanshiGupta any idea why jobs are failing ?

**Comment by divyanshiGupta** [comment]
> @divyanshiGupta any idea why jobs are failing ?

Looks like something changed with jest. As getting similar errors on both of my PRs:
 ```FAIL  components/EditRole.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.
```
The playwright tests are getting timed out.

**Comment by invincibleJai** [comment]
> > @divyanshiGupta any idea why jobs are failing ?
> 
> Looks like something changed with jest. As getting similar errors on both of my PRs:
> 
> ```
>  ● Test suite failed to run
> 
>    Jest encountered an unexpected token
> 
>    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
> 
>    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
> 
>    By default "node_modules" folder is ignored by transformers.
> ```
> 
> The playwright tests are getting timed out.

I attempted to fix it with https://github.com/janus-idp/backstage-plugins/pull/1423

**Comment by invincibleJai** [comment]
@divyanshiGupta can you rebase and update the PR again, thanks!!

**Pull request merged**
