### PR TITLE
feat(bulk-import): add permission checks in bulk import UI

### PR DESCRIPTION
**Pull request by debsmita1**
**Resolves:**
https://issues.redhat.com/browse/RHIDP-1400

### CODE REVIEW

**Review by ciiay — COMMENTED** [review]
Hi @debsmita1 , thanks for the PR 👏  Looks like bottom button margin is a bit off.
image

- If it's admin or user with permission, it should display the `Edit` icon button instead of the `External Link` icon button on the Added repositories row.
- No loading indicator on deleting a row from Added repositories. Maybe we can improve this behavior? Didn't notice this problem until actually tested out.


https://github.com/user-attachments/assets/73d52c06-a452-435a-a5ed-bb0c1b1881cc

**Comment by debsmita1** [comment]
> Hi @debsmita1 , thanks for the PR 👏 Looks like bottom button margin is a bit off. image
> 

Fixed
Screenshot 2024-08-14 at 11 29 23 AM




> * If it's admin or user with permission, it should display the `Edit` icon button instead of the `External Link` icon button on the Added repositories row.

Still working on this

> * No loading indicator on deleting a row from Added repositories. Maybe we can improve this behavior? Didn't notice this problem until actually tested out.

Showing this spinner before the Button

Screenshot 2024-08-14 at 11 28 48 AM


> 
>  pr_bulk_import_permission.mp4

**Comment by ciiay** [comment]
Hi @debsmita1 the button margin and delete spinner work great.

Not sure if it's in scope of this PR, but when I added a repository, it didn't show up in the Added repositories table.

https://github.com/user-attachments/assets/effc8130-3c13-4bfb-b821-788589d98e84

**Comment by ciiay** [comment]
Hi @debsmita1 , can you take a look at the Edit action? Icon flashes between edit icon and external link icon.

https://github.com/user-attachments/assets/06377484-52f9-4838-9c93-c34b358061f8

**Comment by ciiay** [comment]
Another weird thing happened, when I updated `rbac-policy.csv` with my user name, and tried to login again I got the below error.
image

**Review by ciiay — APPROVED** [review]
Works great 👏  Only a small change request. The Organization URL should be trimmed too.
image

**Comment by debsmita1** [comment]
> Works great 👏 Only a small change request. The Organization URL should be trimmed too. image

Fixed 
Screenshot 2024-08-28 at 11 30 43 AM

**Review by invincibleJai — APPROVED** [review]
/lgtm

**Pull request merged**
