### PR TITLE
feat(orchestrator): add auditLog and reorganize endpoints declaration

### PR DESCRIPTION
**Pull request by gabriel-farache**
Add AudditLogger to Orchestrator router

Take on the opportunity to also:
* re-organize endpoint declarations order
* fix a typo

### CODE REVIEW

**Comment by gabriel-farache** [comment]
@rgolangh @batzionb

**Comment by batzionb** [comment]
@gabriel-farache 
so simply adding the auth service does the work?
where are the audits stored?

**Comment by gabriel-farache** [comment]
>so simply adding the auth service does the work?
where are the audits stored?

@batzionb yes, adding the auth service works and allow the AuditLogger to get the actorId from the request

The audit are currently stored in the console, like usual logs so any tool can then scrape them and filter them with `isAuditLog`:
```
backend:start: {"actor":{"actorId":"user:development/guest","hostname":"localhost","ip":"::1","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"},"eventName":"WorkflowsOverview","isAuditLog":true,"level":"debug","message":"Received request to '/v1/workflows/overview' endpoint","meta":{},"plugin":"orchestrator","request":{"body":{},"method":"GET","params":{},"query":{},"url":"/api/orchestrator/workflows/overview"},"service":"backstage","stage":"start","status":"succeeded","timestamp":"2024-06-19 11:21:48"}
```

**Review by batzionb — DISMISSED** [review]

**Comment by rgolangh** [comment]
"stored in the console" means it eventually goes to the container log I guess? if so then this is not really a solution but we can assume that RHDH are handling log storing in some way. We just need the details.
/lgtm

**Comment by gabriel-farache** [comment]
> "stored in the console" means it eventually goes to the container log I guess?

Yes

> we can assume that RHDH are handling log storing in some way

That was my assumption as well

**Comment by rgolangh** [comment]
Can you find out those details, and maybe save the relevant links in the Jira ticket?

**Comment by batzionb** [comment]
> Can you find out those details, and maybe save the relevant links in the Jira ticket?

yeah, we need to understand if the logs are stored in some DB or if once the pod is deleted they are gone

**Comment by gabriel-farache** [comment]
So, nothing is done by RHDH https://redhat-internal.slack.com/archives/C05HGAR2DT5/p1718800085094979?thread_ts=1718800022.132069&cid=C05HGAR2DT5

OCP built-in logging configuration should be used (https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/logging/log-storage#doc-wrapper and https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html/logging/log-collection-and-forwarding#cluster-logging-collector)

I'll create a Jira issue to setup logging storage/collection but this would be highly dependent on what the customer already have in place: if they have en ELK/EFK stack, they'd just need to connect it

**Comment by gabriel-farache** [comment]
@rgolangh https://issues.redhat.com/browse/FLPATH-1421

**Comment by batzionb** [comment]
@gabriel-farache 
PTAL at the lint errors

**Review by batzionb — DISMISSED** [review]

**Comment by batzionb** [comment]
The test is failing because the result of "yarn export-dynamic" of orchestrator-backend plugin changes
You can resolve this by running the following:
```
cd plugins/orchestrator-backend
yarn export-dynamic
cd dist-dynamic
yarn install

```

Add the diff files to the commit

**Comment by gabriel-farache** [comment]
@batzionb So, same error as for #1818
```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
```
I'll try to commit the lock file to see what is failing next

**Review by batzionb — APPROVED** [review]

**Pull request merged**
