### PR TITLE
fix(orchestrator): fix wrong v2 abort endpoint

### PR DESCRIPTION
**Pull request by rgolangh**

### CODE REVIEW

**Comment by gciavarrini** [comment]
Thanks for this fix :) 
Please run `yarn openapi:generate` from `orchestrator-common` folder to fix the failing test (generated files are not up-to-date).

**Comment by batzionb** [comment]
@rgolangh 
PTAL https://github.com/janus-idp/backstage-plugins/actions/runs/10760696754/job/29838966798?pr=2141#step:4:101

**Comment by rgolangh** [comment]
hi

**Comment by rgolangh** [comment]
multi line comment
test

**Review by gciavarrini — APPROVED** [review]
/lgtm

**Pull request merged**
