### PR TITLE
fix(orchestrator): remove field 'variables' from ProcessInstanceDTO

### PR DESCRIPTION
**Pull request by ydayagi**
[FLPATH-1672](https://issues.redhat.com//browse/FLPATH-1672)
https://issues.redhat.com/browse/FLPATH-1672

### CODE REVIEW

**Comment by ydayagi** [comment]
@gabriel-farache @pkliczewski @gciavarrini

**Review by gciavarrini — APPROVED** [review]
/lgtm

**Comment by batzionb** [comment]
@ydayagi 
Please revert this PR
Two reasons:
1. the UI uses the variables field, to remove it you need to adjust the UI
2. it's removed from the API definition, but still returned by the backend, so it isn't consistent. But at least this prevents the UI from being broken

**Comment by batzionb** [comment]
I see now this breaks the build of the plugin
I'll create the revert now

**Pull request merged**
