### PR TITLE
fix(audit-log-node): optimise for the new backend and remove deprecations

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this pull request do

Optimise for the new backend and remove deprecations

### What does this pull request fix:

https://issues.redhat.com/browse/RHIDP-4226

### CODE REVIEW

**Review by schultzp2020 — APPROVED** [review]
/approve
/lgtm

**Comment by schultzp2020** [comment]
@AndrienkoAleksandr please regen the yarn lockfile.

**Review by schultzp2020 — DISMISSED** [review]
/approve
/lgtm

**Review by schultzp2020 — DISMISSED** [review]
/approve
/lgtm

**Comment by AndrienkoAleksandr** [comment]
@schultzp2020 I rebased pr.

**Review by schultzp2020 — APPROVED** [review]
/approve
/lgtm

**Comment by schultzp2020** [comment]
@AndrienkoAleksandr can you rebase again? 😢 We need to merge it faster. 😆

**Review by schultzp2020 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
