### PR TITLE
fix(tekton): update tekton version in the documentation

### PR DESCRIPTION
**Pull request by debsmita1**
**Resolves:**
https://github.com/janus-idp/backstage-plugins/issues/948

Updated tekton version from v1beta1 to v1

https://github.com/janus-idp/backstage-plugins/assets/22490998/36029d4d-6a0f-49eb-8b1c-24fd5e699c4e

### CODE REVIEW

**Comment by invincibleJai** [comment]
@debsmita1 you might need to update 

models like https://github.com/janus-idp/backstage-plugins/blob/main/plugins/tekton/src/models.ts#L4, test data as well

**Comment by debsmita1** [comment]
@invincibleJai updated the PR, PTAL

**Review by invincibleJai — APPROVED** [review]
LGTM

**Comment by invincibleJai** [comment]
there are two references missed

https://github.com/janus-idp/backstage-plugins/blob/main/plugins/topology/src/__fixtures__/workloadNodeData.ts#L1254
https://github.com/janus-idp/backstage-plugins/blob/main/plugins/topology/src/__fixtures__/workloadNodeData.ts#L1695

**Review by invincibleJai — APPROVED** [review]

**Pull request merged**
