### PR TITLE
Add parodos

### LINKED ISSUE #178: 🔌 Plugin: Parodos
## Goal
This epic aims to develop a new Backstage plugin in the Janus repo. This plugin should allow Backstage users to access guided flows driven by the Parodos workflow engine.

## Acceptance criteria
- [ ] Users should be able to xxx (need to flesh out the first version of ACs)
- [ ] 
## Requirements
- [ ] Plugin
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [ ] tbd

## Notes
Parodos workflow engine - community repo: https://github.com/redhat-developer/parodos

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes #178 .

This is a project transfer of https://github.com/parodos-dev/backstage-parodos under janus-idp.

There are 2 new plugins introduced: `parodos` and `parodos-auth`. The `parodos-auth` is implementation of Basic Authentication which is meant to be either temporary or an example. The production deployment is expected to have a specific mechanism in place, aligned with the backend. For that reason, the `parodos-auth` is used conditionally only for the `/parodos` context only.

### CODE REVIEW

**Comment by mareklibra** [comment]
Screenshot from 2023-04-11 09-18-58

---

Screenshot from 2023-04-11 09-19-40

---

Screenshot from 2023-04-11 09-20-35

**Comment by mareklibra** [comment]
@serenamarie125 , recent Notification page:

Screenshot from 2023-04-11 14-58-49

**Comment by invincibleJai** [comment]
> Another question @mareklibra - it looks like you are using the pipeline visualization here? @invincibleJai does it make sense to have shared code between this our pipelines plugins?

Yeah Serena, it does use "@patternfly/react-topology" and we need to evaluate how much of the code is reused and be a common package. 

A similar conversation I had with @tumido as there could be duplicacy among plugins and we need to discuss about how to handle this 

@debsmita1 / @divyanshiGupta FYI

**Comment by mareklibra** [comment]
Synced with ex-home changes.

**Comment by gorkem** [comment]
What would be the way for me to test this plugin? I suppose it needs a Parados running somewhere but I am not sure how to get Parados. Can you post some instructions?

**Comment by mareklibra** [comment]
@gorkem , right, the Parodos backend needs to be running. There's description in `plugins/parodos/README.md` file, part of this PR. Please share your feedback when following the instructions there.

In particular, you need to run the Workflow and Notification service of Parodos (all described there).

Please let me know if you have any difficulties, i.e. on slack.

**Comment by mareklibra** [comment]
Synced with the deprecating repo.

**Comment by christophe-f** [comment]
The 'projects' tab of the plugin is confusing as Backstage has already a catalog where a user (dev) will be expecting to find everything. In this case, the user will have to look in the catalog and another project list. I would imagine that this project would not be available in the Backstage search.

**Comment by pkliczewski** [comment]
> The 'projects' tab of the plugin is confusing as Backstage has already a catalog where a user (dev) will be expecting to find everything. In this case, the user will have to look in the catalog and another project list. I would imagine that this project would not be available in the Backstage search.

It is a Parodos concept. I agree that the name is confusing within Backstage ecosystem. I think we need to align Parodos plugin user experience with Backstage but it will be long discussion/review and I would like to progress with the PR and do the review later.

**Comment by mareklibra** [comment]
Not sure what has happened but we are missing formerly uploaded screenshots here.
So reposting:

Screenshot from 2023-04-11 09-18-58

---

Screenshot from 2023-04-11 09-19-40

---

Screenshot from 2023-04-11 09-20-35

---

Screenshot from 2023-04-11 14-58-49

**Comment by mareklibra** [comment]
Per offline discussion, we are postponing this effort till capacity allows review and faster cooperation.
We keep development at former project home.

**Pull request closed without merging**
