### PR TITLE
feat(artifactory): Rename to jfrog-artifactory

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/janus-idp/backstage-plugins/issues/210

### CODE REVIEW

**Comment by tumido** [comment]
@christophe-f @fmenesesg PTAL

**Review by fmenesesg — APPROVED** [review]

**Comment by tumido** [comment]
@fmenesesg  can you please take one more look to see if this makes sense and test it out?

**Comment by fmenesesg** [comment]
@tumido  I commit a few changes to finish the renaming tasks
I test it and is working correctly PTAL.

**Review by tumido — COMMENTED** [review]
Thank you @fmenesesg! 👍  This looks great!

/lgtm

**Pull request merged**
