### PR TITLE
feat(rbac): center align toast

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes: https://github.com/janus-idp/backstage-plugins/issues/1069

Screenshot 2024-01-23 at 3 28 53 PM

Screenshot 2024-01-19 at 5 07 59 PM

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@parvathyvr I have made the toast centre aligned with the screen. LMK if that looks okay or should be centre aligned with just the list page? Also I have made the alert title bold as required.

**Comment by parvathyvr** [comment]
> @parvathyvr I have made the toast centre aligned with the screen. LMK if that looks okay or should be centre aligned with just the list page? Also I have made the alert title bold as required.

@divyanshiGupta Thanks for making alert title bold.

About centre aligning the toasts-it's okay that the toast is centre aligned to the screen. I think it looks a bit odd because there is some empty space in the toast after the message.
I was checking for some examples in Janus and here are some example that @ShiranHi had captured 👇:

Image-sucess alert
image- info alert

These ones do not have empty space after the message- May be we can follow these examples and i also notice that they are using success alert -so may be we should also use a success alert for role creation instead of the blue banner i had suggested from the backstage design system. WDYT? I hope it is not too much of a change. Let me know -Thanks!

**Comment by divyanshiGupta** [comment]
> > @parvathyvr I have made the toast centre aligned with the screen. LMK if that looks okay or should be centre aligned with just the list page? Also I have made the alert title bold as required.
> 
> @divyanshiGupta Thanks for making alert title bold.
> 
> About centre aligning the toasts-it's okay that the toast is centre aligned to the screen. I think it looks a bit odd because there is some empty space in the toast after the message. I was checking for some examples in Janus and here are some example that @ShiranHi had captured 👇:
> 
> Image-sucess alert image- info alert
> 
> These ones do not have empty space after the message- May be we can follow these examples and i also notice that they are using success alert -so may be we should also use a success alert for role creation instead of the blue banner i had suggested from the backstage design system. WDYT? I hope it is not too much of a change. Let me know -Thanks!

@parvathyvr sure I can try and remove the space. But we are currently using `Alert` from mui and the ones you have showed in the above pictures is using some backstage comp but I dont see it here in the storybook https://backstage.io/storybook/?path=/story/plugins-examples--plugin-with-data. Also this was added based on these designs here https://www.figma.com/file/E6C9X3OSVzlWkW7ZsbxN7s/Administration?type=design&node-id=932-2543&mode=design&t=lQR0Elg6vAJhBzIM-0 so we can have another ticket to change the alert if needed. cc: @invincibleJai

**Comment by parvathyvr** [comment]
> @parvathyvr sure I can try and remove the space. But we are currently using `Alert` from mui and the ones you have showed in the above pictures is using some backstage comp but I dont see it here in the storybook https://backstage.io/storybook/?path=/story/plugins-examples--plugin-with-data. Also this was added based on these designs here https://www.figma.com/file/E6C9X3OSVzlWkW7ZsbxN7s/Administration?type=design&node-id=932-2543&mode=design&t=lQR0Elg6vAJhBzIM-0 so we can have another ticket to change the alert if needed. cc: @invincibleJai

@divyanshiGupta Sure, i had used the dismissable banner in the design. But since i saw those examples in Janus as shared in the screenshots earlier, i was wondering if we should align with them. But if they are not available in the storybook, we can look into it later. But i guess we could remove the excess space in the dismissable banner- Thank you!

**Comment by divyanshiGupta** [comment]
> > @parvathyvr sure I can try and remove the space. But we are currently using `Alert` from mui and the ones you have showed in the above pictures is using some backstage comp but I dont see it here in the storybook https://backstage.io/storybook/?path=/story/plugins-examples--plugin-with-data. Also this was added based on these designs here https://www.figma.com/file/E6C9X3OSVzlWkW7ZsbxN7s/Administration?type=design&node-id=932-2543&mode=design&t=lQR0Elg6vAJhBzIM-0 so we can have another ticket to change the alert if needed. cc: @invincibleJai
> 
> @divyanshiGupta Sure, i had used the dismissable banner in the design. But since i saw those examples in Janus as shared in the screenshots earlier, i was wondering if we should align with them. But if they are not available in the storybook, we can look into it later. But i guess we could remove the excess space in the dismissable banner- Thank you!

Sure @parvathyvr I will remove the space. Can you also create a ticket mentioning all that needs to be updated regarding this toast from UX perspective? That will be really helpful. Thanks!

**Comment by divyanshiGupta** [comment]
> > @parvathyvr sure I can try and remove the space. But we are currently using `Alert` from mui and the ones you have showed in the above pictures is using some backstage comp but I dont see it here in the storybook https://backstage.io/storybook/?path=/story/plugins-examples--plugin-with-data. Also this was added based on these designs here https://www.figma.com/file/E6C9X3OSVzlWkW7ZsbxN7s/Administration?type=design&node-id=932-2543&mode=design&t=lQR0Elg6vAJhBzIM-0 so we can have another ticket to change the alert if needed. cc: @invincibleJai
> 
> @divyanshiGupta Sure, i had used the dismissable banner in the design. But since i saw those examples in Janus as shared in the screenshots earlier, i was wondering if we should align with them. But if they are not available in the storybook, we can look into it later. But i guess we could remove the excess space in the dismissable banner- Thank you!

@parvathyvr I have removed the space and aligned the toast with above images. PTAL.

**Comment by parvathyvr** [comment]
> @parvathyvr I have removed the space and aligned the toast with above images. PTAL.

Thank you @divyanshiGupta! LGTM.

**Review by parvathyvr — APPROVED** [review]

**Pull request merged**
