### PR TITLE
fix(orchestrator): handle fetch error that doesn't throw error

### PR DESCRIPTION
**Pull request by ydayagi**
FLAPTH-1725
https://issues.redhat.com/browse/FLPATH-1725

### CODE REVIEW

**Comment by ydayagi** [comment]
@gciavarrini @batzionb

**Comment by batzionb** [comment]
@ydayagi 
please remove the empty changeset file

**Comment by batzionb** [comment]
use this method to generate the error, so we'll have a consistent error message structure 
https://github.com/janus-idp/backstage-plugins/blob/orchestrator-1.3/plugins/orchestrator-backend/src/service/SonataFlowService.ts#L193

**Comment by ydayagi** [comment]
change not needed

**Pull request closed without merging**
