### PR TITLE
docs(Quay): add link to instructions to generate token

### PR DESCRIPTION
**Pull request by evanshortiss**

### CODE REVIEW

**Comment by dzemanov** [comment]
@evanshortiss can you please rebase the branch to update the changes and fix `After 'yarn install', workspace is dirty!`

**Comment by evanshortiss** [comment]
@dzemanov I haven't changed anything related to Yarn, lockfiles, etc. I believe that's a broader issue, outside the scope of this PR?

**Comment by dzemanov** [comment]
@evanshortiss yes, but there were changes in main in `yarn.lock` that need to be incorporated here, otherwise build tests fail because `yarn.lock` differs after install.

**Comment by evanshortiss** [comment]
Gotcha, I _think_ it's rebased with the latest changes now.

**Review by AndrienkoAleksandr — APPROVED** [review]

**Pull request merged**
