### PR TITLE
feat(kiali): workloads page list

### PR DESCRIPTION
**Pull request by josunect**
This is still in Draft. 

Some TODOs: 

- [X] health indicator not showing 
- [x] Sortable columns
- [X] Improve styles 
- [X] Workloads are shown with Details "Waypoint Proxy"
- [X] JS error: 
```Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of ForwardRef(Tooltip)
```

TODOs for the Table component:

- [ ] Filtering
- [ ] Pagination

### CODE REVIEW

**Comment by aljesusg** [comment]
I would remove the From toolbar selector and refresh for now and the filters option in table, we need to fix styles but looks good I'll check the code. Good job

image

**Comment by aljesusg** [comment]
It's weird Is this working for you?

yarn start not work

image

Entity view is not working the overview

image


And kiali menu is not wrking neither 

image

**Comment by josunect** [comment]
Sorry! I forgot to check `yarn start.` I'm reviewing it now. 

Regarding the Kiali page, it is working for me: 

image

image

Not sure what can be happening... Do you have any log errors?

**Comment by aljesusg** [comment]
> Sorry! I forgot to check `yarn start.` I'm reviewing it now.
> 
> Regarding the Kiali page, it is working for me:
> 
> image
> 
> image
> 
> Not sure what can be happening... Do you have any log errors?

well I forgot toa dd route not it's working but not the entity view i need to check

**Review by aljesusg — APPROVED** [review]
LGFM

**Pull request merged**
