### PR TITLE
chore(topology): update topology to be compatible with backstage 1.18.x

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes: https://github.com/janus-idp/backstage-plugins/issues/830

Updated topology plugin dependencies to make it compatible with 1.18.4 (latest version)

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @debsmita1 @invincibleJai

**Review by invincibleJai — APPROVED** [review]
LGTM

**Comment by divyanshiGupta** [comment]
@tumido topology npm package hasnt been updated with this PR yet, same with this one https://github.com/janus-idp/backstage-plugins/pull/815 for tekton plugin. Am I missing something that triggers the release process or is this something else?

**Comment by tumido** [comment]
It should be released in `1.15.7`, isn't it?

https://github.com/janus-idp/backstage-plugins/commits/%40janus-idp/backstage-plugin-topology%401.15.7/

I think the issues is that `chore` doesn't trigger a release... So it was caused by a mislabeled PR.

**Comment by divyanshiGupta** [comment]
> It should be released in `1.15.7`, isn't it?
> 
> 
> 
> https://github.com/janus-idp/backstage-plugins/commits/%40janus-idp/backstage-plugin-topology%401.15.7/
> 
> 
> 
> I think the issue is that `chore` doesn't trigger a release... So it was caused by a mislabeled PR.

Oh, got it. Yes the new version should be 1.15.7. I see that the new versions for both plugins got released as one of the fixes PR got merged so we should be good now. Will make sure not to use chore in case of immediate releases requirement. Thanks.

**Pull request merged**
