### PR TITLE
feat(rbac): show rules count in overview page

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Story: https://issues.redhat.com/browse/RHIDP-2770

Screenshot:
Screenshot 2024-06-27 at 6 44 14 PM

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @ShiranHi

**Comment by ShiranHi** [comment]
@divyanshiGupta looks good to me, thank you

**Review by ciiay — CHANGES_REQUESTED** [review]
Tested working good. Just left a few small comments.

**Comment by divyanshiGupta** [comment]
Updated rbac-common dep in this PR after this PR https://github.com/janus-idp/backstage-plugins/pull/1795 got merged

**Comment by ciiay** [comment]
LGTM

**Pull request merged**
