### PR TITLE
fix(orchestrator): fixes v2/instances endpoint

### PR DESCRIPTION
**Pull request by jkilzi**
The `start` and `end` fields of the `ProcessInstance`are annotated as `strings` instead of `Date` now. The format of the string is provided as a hint for the developer as a comment (date-time)  due to limitations in the OpenAPI code generator.

### CODE REVIEW

**Comment by jkilzi** [comment]
The "Build all packages" task is failing due to a type-check error in our code base, unrelated to the changes I've made.
@caponetto [PTAL](https://github.com/janus-idp/backstage-plugins/actions/runs/8444061539/job/23128910963?pr=1412#step:3:585) :pray: 

The "Test" job failed due to a code styling issue in [a readme file located outside of  our code base](https://github.com/janus-idp/backstage-plugins/actions/runs/8444061539/job/23128910784?pr=1412#step:3:303) :shrug:

**Comment by batzionb** [comment]
> The "Build all packages" task is failing due to a type-check error in our code base, unrelated to the changes I've made. @caponetto [PTAL](https://github.com/janus-idp/backstage-plugins/actions/runs/8444061539/job/23128910963?pr=1412#step:3:585) 🙏
> 
> The "Test" job failed due to a code styling issue in [a readme file located outside of our code base](https://github.com/janus-idp/backstage-plugins/actions/runs/8444061539/job/23128910784?pr=1412#step:3:303) 🤷

@jkilzi this PR https://github.com/janus-idp/backstage-plugins/pull/1409 resolved the issue
the tests should be rerun

**Comment by jkilzi** [comment]
I'll reopen this PR from a feature branch istead from my main branch

**Pull request closed without merging**
