### PR TITLE
fix(kiali): remove IstioConfig extra, Fix links and add kiali control

### PR DESCRIPTION
**Pull request by aljesusg**
Some fix:

- Remove IstioConfig List from Resources Card
- Fixed Links for entity view and standalone
- Added routes for entity view
- Add setup kiali playwright
- Add kiali control

Close:

- https://issues.redhat.com/browse/OSSM-4611
- https://issues.redhat.com/browse/OSSM-6256
- https://issues.redhat.com/browse/OSSM-6055
- https://issues.redhat.com/browse/OSSM-5963

## Kiali control versions

Screenshot from 2024-05-02 15-23-46
Screenshot from 2024-05-02 15-23-36

## Run test locally

Info added to DEVELOPMENT.md

To run the UI tests locally, take the following steps:

First, install playwright dependencies:

```bash
$ yarn install --with-deps chromium
```

The remaining steps need to be run in parallel.

Launch the plugin:

```bash
$ cd plugins/${plugin} && yarn start
```

Finally, launch the UI tests (headless):

```bash
$ cd plugins/${plugin} && yarn run ui-test
```

If you wish to see the test runner UI, instead of headless:

```bash
$ cd plugins/${plugin} && yarn playwright test --ui
```

Test results from the headless run will be available in `plugins/${plugin}/playwright-report` folder.

### CODE REVIEW

**Comment by aljesusg** [comment]
@AndrienkoAleksandr we need your approval here due the yarn.lock, we didn't add it these libraries so it seems that a Pr was merged without the yarn.lock. The CI didn't pass if yarn.lock is not right ☹️

**Review by leandroberetta — APPROVED** [review]
lgtm

**Comment by aljesusg** [comment]
@janus-idp/maintainers can you review this? Automerge is not triggered

**Review by nickboldt — APPROVED** [review]

**Pull request merged**
