### PR TITLE
fix(rbac): rework condition policies to bound them to RBAC roles

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this pull request do

Rework condition policies to bound them to RBAC roles

### What issue is referenced in this pull request?

https://issues.redhat.com/browse/RHIDP-1526
https://issues.redhat.com/browse/RHIDP-1616

### How to test it:

You need to have two users: admin and test user.  "user:default/logarifm" is my test user and member of group:defalt/team-a. Token should be retrieved for admin user.

#### Let's create test role:

`
curl -X POST "http://localhost:7007/api/permission/roles" -d '{ "memberReferences":  [ "user:default/logarifm" ], "name": "role:default/test" }' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

#### Let's create condition to display for user logarifm only his own catalogs:

`
curl -X POST "http://localhost:7007/api/permission/roles/conditions" -d '{"result":"CONDITIONAL","roleEntityRef": "role:default/test","pluginId":"catalog","resourceType":"catalog-entity", "permissionMapping": ["read"], "conditions":{"rule":"IS_ENTITY_OWNER","resourceType":"catalog-entity","params":{"claims":["group:default/team-a"]}}}' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

OR you can use criteria "not" and hide API catalogs for user logarifm:

`
curl -X POST "http://localhost:7007/api/permission/roles/conditions" -d '{"result":"CONDITIONAL","roleEntityRef": "role:default/test","pluginId":"catalog","resourceType":"catalog-entity","permissionMapping": ["read"],"conditions":{"not":{"rule":"IS_ENTITY_KIND","resourceType":"catalog-entity","params":{"kinds":["Api"]}}}}' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

Login like user logarifm and check catalog UI.

Retrieve list of all conditions: 

`
curl -X GET "http://localhost:7007/api/permission/roles/conditions" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

Filter conditions with the query params:

`
curl -X GET "http://localhost:7007/api/permission/roles/conditions?roleEntityRef=role:default/test&&pluginId=catalog&&resourceType=catalog-entity&&actions=read" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

#### Get condition by id:

`
curl -X GET "http://localhost:7007/api/permission/roles/conditions/1" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

#### Update condition policy to display for logarifm user his own catalogs and list user groups:

`
curl -X PUT "http://localhost:7007/api/permission/roles/conditions/1" -d '{"result":"CONDITIONAL","roleEntityRef":"role:default/test", "pluginId":"catalog","resourceType":"catalog-entity","permissionMapping": ["read"],"conditions":{"anyOf":[{"rule":"IS_ENTITY_OWNER","resourceType":"catalog-entity","permissions": [{"name": "catalog.entity.read", "action": "read"}],"params":{"claims":["group:default/team-a"]}},{"rule":"IS_ENTITY_KIND","resourceType":"catalog-entity","params":{"kinds":["Group"]}}]}}' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

#### Delete condition by id:

`
curl -X DELETE "http://localhost:7007/api/permission/roles/conditions/1" -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v
`

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@AndrienkoAleksandr is there going to be an api endpoint for getting all the conditions that were applied while role creation? Like we have for the policies `/api/permission/policies/role/${namespace}/${name}` so that we can show the existing data to users? Also since we are updating/deleting conditions based on the id we will need that id for each condition so that we can enable update/delete from UI. Maybe this id can be part of the api response for getting all conditions for a specific role?

**Comment by divyanshiGupta** [comment]
@AndrienkoAleksandr after these changes will it be possible to just update the permission policy without having to update the condition that was applied after creating that policy, similar to what you have shown in the description above?

**Comment by divyanshiGupta** [comment]
> @AndrienkoAleksandr after these changes will it be possible to just update the permission policy without having to update the condition that was applied after creating that policy, similar to what you have shown in the description above?

@AndrienkoAleksandr wdyt about this?

**Comment by AndrienkoAleksandr** [comment]
> @AndrienkoAleksandr after these changes will it be possible to just update the permission policy without having to update the condition that was applied after creating that policy, similar to what you have shown in the description above?
@AndrienkoAleksandr wdyt about this?

I think condition should be executed without corresponding permission policy check. I fixed that in the pull request and I removed  unnecessary permission policy creation from description:

~~#### Let's provide read catalog permission:~~

~~curl -X POST "http://localhost:7007/api/permission/policies" -d '[{"entityReference": "role:default/test", "permission": "catalog-entity", "policy": "read", "effect":"allow"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v~~

I remember we consider to make this  fix in the working group meeting thanks you reminded me

**Comment by divyanshiGupta** [comment]
> > @AndrienkoAleksandr after these changes will it be possible to just update the permission policy without having to update the condition that was applied after creating that policy, similar to what you have shown in the description above?
> > @AndrienkoAleksandr wdyt about this?
> 
> I think condition should be executed without corresponding permission policy. I fixed that in the pull request and I removed unnecessary permission policy creation from description:
> 
> ~#### Let's provide read catalog permission:~
> 
> ~curl -X POST "http://localhost:7007/api/permission/policies" -d '[{"entityReference": "role:default/test", "permission": "catalog-entity", "policy": "read", "effect":"allow"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v~
> 
> I remember we consider to make this fix in the working group meeting thanks you reminded me

@AndrienkoAleksandr you mean that current api for creating permission policies which is `curl -X POST "http://localhost:7007/api/permission/policies" -d '[{"entityReference": "role:default/test", "permission": "catalog-entity", "policy": "read", "effect":"allow"}]' -H "Content-Type: application/json" -H "Authorization: Bearer $token" -v` will remain as if and can be updated irrespective of the condition applied right? Or is there some changes in the api? Just want to confirm if permission policies and conditions are independent of each other or not.

**Comment by AndrienkoAleksandr** [comment]
> @divyanshiGupta Just want to confirm if permission policies and conditions are independent of each other or not.

Yes, these APIs are independent. I didn't touch the simple permission policy API (http://some-host:port/api/permission/policies). I changed the code evaluation conditional permissions as follows:

- If a user creates a condition and doesn't have a simple permission with the resource type then the backend will simply find this condition and evaluate it (in this case, the backend sends the condition to the corresponding plugin, where the plugin analyzes the condition and renders filtered data)
- If a user has a simple permission policy with the resource type and doesn't have any conditions, then the backend will evaluate this simple permission.
- If a user has both a simple permission policy with a resource type and a conditional policy, then the backend will evaluate only the condition. In this PR, I provided higher priority for the condition compared to the simple policy.

**Review by PatAKnight — CHANGES_REQUESTED** [review]
Looks good so far, just a couple of things. 

Can we also get some updates to the [api docs](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/docs/apis.md#conditions)?

Also, wouldn't this be considered a breaking change? We are changing the conditions endpoints and the old ones would no longer be valid.

**Comment by AndrienkoAleksandr** [comment]
I updated doc. Additionally, I made some modifications to simplify frontend requests by hiding permission names. I'm not sure if the frontend will always have this information.

> @PatAKnight : Also, wouldn't this be considered a breaking change? We are changing the conditions endpoints and the old ones would no longer be valid.

Yes, it is, but unfortunately, we couldn't make migrations for old conditions.

**Comment by PatAKnight** [comment]
Do you mind updating your commit message from `fix(rbac): rework condition policies to bound them to RBAC roles` to `fix(rbac)!: rework condition policies to bound them to RBAC roles`. Since this is a breaking change. 

Also, it looks like you have a linting error which is causing a failure.

**Comment by AndrienkoAleksandr** [comment]
> @PatAKnight: Do you mind updating your commit message from fix(rbac): rework condition policies to bound them to RBAC roles to fix(rbac)!: rework condition policies to bound them to RBAC roles. Since this is a breaking change.
Also, it looks like you have a linting error which is causing a failure.

Done.

**Review by PatAKnight — COMMENTED** [review]
Last request, but can you also update the [endpoints](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/docs/apis.md#post-condition) in the documentation?

**Comment by AndrienkoAleksandr** [comment]
> Last request, but can you also update the [endpoints](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/docs/apis.md#post-condition) in the documentation?

Done.

**Review by PatAKnight — APPROVED** [review]
/lgtm

**Pull request merged**
