### PR TITLE
feat(deps): update to backstage 1.29

### PR DESCRIPTION
**Pull request by schultzp2020**
fixes https://issues.redhat.com/browse/RHIDP-2791

### CODE REVIEW

**Comment by schultzp2020** [comment]
@mareklibra @ydayagi can you please help me fix the token deprecations in the notifications plugin?

**Comment by ydayagi** [comment]
> @mareklibra @ydayagi can you please help me fix the token deprecations in the notifications plugin? https://backstage.io/docs/backend-system/core-services/http-auth/ https://github.com/backstage/backstage/releases/tag/v1.29.0

@schultzp2020 I don't know what is the problem that you are facing. But, you can delete the notifications plugin. At least comment it out somehow. We are not using it anymore. There is an upstream plugin now.

**Comment by batzionb** [comment]
verified orchestrator plugin

**Review by nickboldt — DISMISSED** [review]
tests pass, some plugin owners have +1'd, so +1 from me too.  

What. could. go. wrong?

**Comment by yashoswalyo** [comment]
feedback, matomo plugin looks fine

**Review by yashoswalyo — APPROVED** [review]

**Comment by ciiay** [comment]
Verified that rbac plugin works good.

**Pull request merged**
