### PR TITLE
chore(keycloak-backend): display cause of error while logging error

### PR DESCRIPTION
**Pull request by 04kash**
This PR makes changes to the keycloak plugin to display cause of error while logging error. 

Before: 
```
2024-09-27T16:59:34.697Z catalog error Error while syncing Keycloak users and groups fetch failed class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=51434a22-6c36-4930-a7f9-27ef8da4c5a1 name=TypeError stack=TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchWithError (file:///home/kmittal/repos/backstage-plugins/node_modules/@keycloak/keycloak-admin-client/lib/utils/fetchWithError.js:11:22)
    at async getToken (file:///home/kmittal/repos/backstage-plugins/node_modules/@keycloak/keycloak-admin-client/lib/utils/auth.js:46:22)
    at async KeycloakAdminClient.auth (file:///home/kmittal/repos/backstage-plugins/node_modules/@keycloak/keycloak-admin-client/lib/client.js:67:47)
    at async KeycloakOrgEntityProvider.read (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts:232:5)
    at async fn (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts:267:13)
    at async TaskWorker.fn (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/PluginTaskSchedulerImpl.ts:137:9)
    at async TaskWorker.runOnce (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:156:13)
    at async <anonymous> (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:76:31) status=undefined
```

Now: 

```
2024-09-27T16:57:20.284Z catalog error Error while syncing Keycloak users and groups fetch failed class=KeycloakOrgEntityProvider taskId=KeycloakOrgEntityProvider:default:refresh taskInstanceId=5330d834-bf79-48fd-bbaf-83b88875db0e name=TypeError cause=Error: self-signed certificate stack=TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchWithError (file:///home/kmittal/repos/backstage-plugins/node_modules/@keycloak/keycloak-admin-client/lib/utils/fetchWithError.js:11:22)
    at async getToken (file:///home/kmittal/repos/backstage-plugins/node_modules/@keycloak/keycloak-admin-client/lib/utils/auth.js:46:22)
    at async KeycloakAdminClient.auth (file:///home/kmittal/repos/backstage-plugins/node_modules/@keycloak/keycloak-admin-client/lib/client.js:67:47)
    at async KeycloakOrgEntityProvider.read (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts:232:5)
    at async fn (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts:267:13)
    at async TaskWorker.fn (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/PluginTaskSchedulerImpl.ts:137:9)
    at async TaskWorker.runOnce (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:156:13)
    at async <anonymous> (/home/kmittal/repos/backstage-plugins/plugins/keycloak-backend/node_modules/@backstage/backend-defaults/src/entrypoints/scheduler/lib/TaskWorker.ts:76:31) status=undefined
```

Fixes: https://issues.redhat.com/browse/RHIDP-4219

### CODE REVIEW

**Comment by dzemanov** [comment]
Works as expected 🎉

**Review by JessicaJHee — APPROVED** [review]
LGTM!

**Pull request merged**
