### PR TITLE
docs(jfrog): be explicit about JFrog SaaS target URI

### PR DESCRIPTION
**Pull request by timdittler**
I thought, it would have to add the API endpoint. So better to be explicit :)

### CODE REVIEW

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
Think you @timdittler for a PR. 🙂 I agree, it's always better to be explicit in docs.

**Comment by tumido** [comment]
@timdittler can you please run `yarn prettier:fix` on this? It complains in the CI

```diff
-       target: 'http://<hostname>:8082'  # or https://<customer>.jfrog.io
+       target: 'http://<hostname>:8082' # or https://<customer>.jfrog.io
```

**Comment by timdittler** [comment]
> @timdittler can you please run yarn prettier:fix on this? It complains in the CI

done

**Comment by timdittler** [comment]
What's left to merge this?

**Comment by tumido** [comment]
@timdittler, nothing on your side and there was a bit of a backlog on my side. I've had to manually allow CI to run on this and once it finishes, it should be good to 🚢  🙂

**Pull request merged**
