### PR TITLE
feat(rbac): add type checks with generics for audit log

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
# What does this pull request do:

Add type checks for audit log metadata object for type safety.

### CODE REVIEW

**Review by Zaperex — APPROVED** [review]
/lgtm

**Review by schultzp2020 — DISMISSED** [review]
/lgtm
/approve
/cherry-pick 1.2

**Review by schultzp2020 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
