### PR TITLE
chore(ocm-backend): add standalone dev environment for OCM backend

### LINKED ISSUE #600: OCM backend needs a standalone dev environment
We need to provide a standalone dev environment for plugins that interact with backstage catalog so we can eventually remove `packages` folder and develop plugins independently.

Please take a look at the OCM backend plugin and implement a catalog backend similar to the implementation for Keycloak plugin https://github.com/janus-idp/backstage-plugins/pull/543

### PR DESCRIPTION
**Pull request by Zaperex**
### What issue does this PR resolve?
Fixes #600

### CODE REVIEW

**Review by RobotSail — APPROVED** [review]
LGTM

**Comment by invincibleJai** [comment]
@Zaperex will be good to update the README as well

I tried below

image

and are there any steps that need to be followed to verify?

**Comment by Zaperex** [comment]
I think that should be expected since the data is displayed via the frontend ocm plugin.

**Comment by Zaperex** [comment]
I'll take a look to see if there's any API endpoints we can suggest in the CONTRIBUTING.md to verify that the backend data is being provided correctly

**Comment by Zaperex** [comment]
It seems you can query the mock data with `http://localhost:7007/api/ocm/status`

**Review by invincibleJai — APPROVED** [review]
LGTM

**Pull request merged**
