### PR TITLE
Add image registry plugin and api client

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes: https://github.com/janus-idp/backstage-plugins/issues/300

Screenshot 2023-04-28 at 4 38 51 PM

### CODE REVIEW

**Review by tumido — APPROVED** [review]
Great prototype! ❤️ 

Love it! Let's get this merged and iterate over it in follow up PRs. 🙂

**Comment by tumido** [comment]
@divyanshiGupta seems like prettier is complaining.

**Review by tumido — APPROVED** [review]

**Comment by divyanshiGupta** [comment]
> @divyanshiGupta seems like prettier is complaining.

@tumido yeah there was some issue with the tekton README. Not sure how it got merged though. I have fixed the issue.

**Comment by tumido** [comment]
@divyanshiGupta it was merged manually despite failing CI. Not good.

**Pull request merged**
