### PR TITLE
fix(orchestrator): improve error handling for incorrect nextWorkflow IDs

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes: [FLPATH-1748](https://issues.redhat.com//browse/FLPATH-1748)

Handles the case when a workflow instance result references next nonexisting workflow ID.

### CODE REVIEW

**Comment by mareklibra** [comment]
Screenshot from 2024-10-03 10-55-16

**Review by gciavarrini — APPROVED** [review]
I'm ok with this PR, but i think we should also propagate the error from sonataflow. It's part of epic [FLPATH-1724](https://issues.redhat.com/browse/FLPATH-1724) work.

**Comment by gciavarrini** [comment]
@mareklibra I've just realized that there is one sonarcloud issue. can you fix it?

**Comment by mareklibra** [comment]
> I've just realized that there is one sonarcloud issue. can you fix it?
Done

**Review by gciavarrini — APPROVED** [review]
/lgtm

**Comment by mareklibra** [comment]
Rebased only

**Pull request merged**
