### PR TITLE
chore(deps): updated yarn.lock to fix yarn workspace app add command error

### PR DESCRIPTION
**Pull request by ciiay**
### What does this PR do?
chore(deps): updated yarn.lock to fix yarn workspace app add command error
This fix excludes fix for ""@janus-idp/shared-react@2.6.3":" as it's been included in #1731 

Signed-off-by: Yi Cai (yicai@redhat.com)

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
error when run `yarn workspace app add` command
For example:
```
error Invariant Violation: expected workspace package to exist for "@babel/core"
    at invariant (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:2318:15)
    at _loop2 (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:91024:9)
    at PackageHoister.init (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:91083:19)
    at PackageLinker.getFlatHoistedTree (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:48552:20)
    at PackageLinker.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:48563:27)
    at Generator.next (<anonymous>)
    at step (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:310:30)
    at /opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:328:14
    at new Promise (<anonymous>)
    at new F (/opt/homebrew/Cellar/yarn/1.22.21/libexec/lib/cli.js:5540:28)
```

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x]  [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x]  [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x]  [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ]  [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x]  [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x]  [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ]  [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ]  [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ]  [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers
Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
yarn lock update also included in #1731 because the PR failed without it. Assuming I can safely close this; if that's wrong and you want to rebase it, please reopen and do so.

**Comment by ciiay** [comment]
@nickboldt #1731 doesn't have the fix this PR provides. Reopened it. Please take a look. Thanks.

**Comment by ciiay** [comment]
Oh I don't have the access to reopen this PR. Can you help me with it?

**Comment by nickboldt** [comment]
Seems I can't reopen it either. Can you create a new one that doesn't have merge conflicts?

**Comment by ciiay** [comment]
Raised ##1735 for the same fix.

**Pull request closed without merging**
