### PR TITLE
fix(plugins): remove React.FC types

### PR DESCRIPTION
**Pull request by schultzp2020**
## Description

Please explain the changes you made here.

Removes React.FC types to be consistent with [Backstage ADRs](https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr006-avoid-react-fc.md). 

## Which issue(s) does this PR fix

No applicable related issue; however, there were a few instances where components were passed a `children` prop and the components did nothing with them.

### CODE REVIEW

**Review by RobotSail — APPROVED** [review]
LGTM

**Review by tumido — APPROVED** [review]
/lgtm
/approve

@invincibleJai please review for Tekton and Topology changes

**Comment by invincibleJai** [comment]
Changes look good, @schultzp2020 pls rebase it then will verify it once

**Comment by schultzp2020** [comment]
> Changes look good, @schultzp2020 pls rebase it then will verify it once

@invincibleJai done

**Review by invincibleJai — APPROVED** [review]
LGTM, Verified Topology and Tekton plugins

**Pull request merged**
