### PR TITLE
fix(keycloak-backend): delete unused dev dependencies and update test

### PR DESCRIPTION
**Pull request by dzemanov**
## General

- Delete unused dev dependencies
- Use `mockServices rootConfig` instead of `ConfigReader` in tests

## Related to

[RHIDP-4056](https://issues.redhat.com/browse/RHIDP-4056)

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Optional, but I think you can use `type` for all @keycloak/keycloak-admin-client library imports. And after that you can move this library to the dev dependency.

**Review by AndrienkoAleksandr — COMMENTED** [review]
Optional, but I think you can use `type` for all @keycloak/keycloak-admin-client library imports. And after that you can move this library to the dev dependency.

**Comment by dzemanov** [comment]
> Optional, but I think you can use `type` for all @keycloak/keycloak-admin-client library imports. And after that you can move this library to the dev dependency.

Thank you for the review. You are totally right, the imports can be changed to type, I will update them. However, `@keycloak/keycloak-admin-client` can't be moved to dev deps, look at for example this [section](https://github.com/janus-idp/backstage-plugins/blob/main/plugins/keycloak-backend/src/providers/KeycloakOrgEntityProvider.ts#L201-L209).

**Review by AndrienkoAleksandr — COMMENTED** [review]
Looks good to me, @schultzp2020 ?

**Review by schultzp2020 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
