### PR TITLE
chore(deps): migrate from openapi to openapi-ts

### PR DESCRIPTION
**Pull request by schultzp2020**
Migrate from openapi (deprecated) to openapi-ts

### CODE REVIEW

**Review by nickboldt — COMMENTED** [review]
seems reasonable other than the usual test failures. 

```
Error: @janus-idp/backstage-scaffolder-backend-module-servicenow#test: command (/home/runner/work/backstage-plugins/backstage-plugins/plugins/servicenow-actions) yarn run test exited (1)
```

Is this a case where after we merge this the tests will work for subsequent runs, but this is a temporarily breaking change that affects the tests?

**Comment by schultzp2020** [comment]
@nickboldt PTAL?

**Comment by nickboldt** [comment]
Paul says "just merge it anyway" so here we go...

**Pull request merged**
