### PR TITLE
chore(deps): rebase 1.2.x plugins to their latest patch versions

### PR DESCRIPTION
**Pull request by kim-tsao**
Many plugins in the 1.2.x branch do not have room to bump the patch version for an upcoming CVE fix.  This PR rebases the affected plugins to their latest patch versions (just before the Backstage 1.27 update).  

The  following backports should not regress the 1.2.x functionality as discussed with @schultzp2020 :

* https://github.com/janus-idp/backstage-plugins/pull/1756
* https://github.com/janus-idp/backstage-plugins/pull/1811
* https://github.com/janus-idp/backstage-plugins/pull/1774
* https://github.com/janus-idp/backstage-plugins/pull/1809  cc @riginoommen 

Fixes: https://issues.redhat.com/browse/RHIDP-4393

### CODE REVIEW

**Review by rm3l — COMMENTED** [review]
~@debsmita1 I just tested this PR, and can confirm both https://issues.redhat.com/browse/RHIDP-4067 and https://issues.redhat.com/browse/RHIDP-3868 are fixed.~

~However, I noticed what I think could be a regression: when trying to import new repos, the "Create pull request" button remains disabled regardless of the repos selected. See the screencast attached:~

~Do you confirm this behavior on your end?~

**Comment by rm3l** [comment]
Whoops - wrong PR 🤦🏿

**Comment by PatAKnight** [comment]
Looks good to me. Most of it was just updating to the `LoggerService`. I am going to wait to give an approval in case any of the other teams that are impacted want to take a look as well.

**Review by yashoswalyo — COMMENTED** [review]
LGTM

**Comment by mareklibra** [comment]
LGTM - orchestrator

**Review by PatAKnight — APPROVED** [review]
/lgtm

**Review by AndrienkoAleksandr — APPROVED** [review]

**Pull request merged**
