### PR TITLE
fix(rbac): correct plugin ID matching to permission policy

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
What does this pull request fix:

https://issues.redhat.com/browse/RHIDP-2374

### CODE REVIEW

**Review by PatAKnight — COMMENTED** [review]
Tested and it worked for me, going to hold off on giving this a looks good in case @divyanshiGupta wants to also take a look.

**Comment by divyanshiGupta** [comment]
@AndrienkoAleksandr Code looks good to me. Will test it locally once and give +1 if everything works fine.

**Review by divyanshiGupta — COMMENTED** [review]
Tested locally. Works as expected.

/approve

**Review by PatAKnight — APPROVED** [review]
LGTM

**Pull request merged**
