### PR TITLE
chore: sync yarn.lock

### PR DESCRIPTION
**Pull request by invincibleJai**
Running yarn install on main results in the following diff

### CODE REVIEW

**Comment by caponetto** [comment]
Thanks @invincibleJai!
I wonder if we could have a check after [this step](https://github.com/janus-idp/backstage-plugins/blob/main/.github/actions/build/action.yaml#L19)
Something like this
```yaml
    - name: "Check yarn.lock"
      shell: bash
      run: |
        echo "Check yarn.lock"
        git diff yarn.lock;
        [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]
```
The build would break if there is a diff in the lock.

**Review by karthikjeeyar — APPROVED** [review]
/lgtm

**Comment by invincibleJai** [comment]
> Thanks @invincibleJai! I wonder if we could have a check after [this step](https://github.com/janus-idp/backstage-plugins/blob/main/.github/actions/build/action.yaml#L19) Something like this
> 
> ```yaml
>     - name: "Check yarn.lock"
>       shell: bash
>       run: |
>         echo "Check yarn.lock"
>         git diff yarn.lock;
>         [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]
> ```
> 
> The build would break if there is a diff in the lock.

yeah we should be adding this

@kadel ^^ and if you can approve the PR

**Comment by gashcrumb** [comment]
> > Thanks @invincibleJai! I wonder if we could have a check after [this step](https://github.com/janus-idp/backstage-plugins/blob/main/.github/actions/build/action.yaml?rgh-link-date=2024-01-30T13%3A58%3A15Z#L19) Something like this
> > ```yaml
> >     - name: "Check yarn.lock"
> >       shell: bash
> >       run: |
> >         echo "Check yarn.lock"
> >         git diff yarn.lock;
> >         [ "0" == "$(git diff yarn.lock | wc -l | tr -d ' ')" ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The build would break if there is a diff in the lock.
> 
> yeah we should be adding this
> 
> @kadel ^^ and if you can approve the PR

BTW I created https://github.com/janus-idp/backstage-plugins/issues/1169 and will shortly also create a similar issue for backstage-showcase.

**Pull request merged**
